# Project information
site_name: River
site_description: Online machine learning in Python
site_author: The Fellowship of Online Machine Learning
site_url: https://riverml.xyz
docs_dir: docs/linkified

# Repository
repo_name: online-ml/river
repo_url: https://github.com/online-ml/river
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019 - 2026

# Enable strict mode
extra:
  zensical_strict: true

# Navigation
nav:
  - Introduction:
    - introduction/installation.md
    - introduction/basic-concepts.md
    - Getting started:
      - introduction/getting-started/index.md
      - introduction/getting-started/binary-classification.md
      - introduction/getting-started/concept-drift-detection.md
      - introduction/getting-started/multiclass-classification.md
      - introduction/getting-started/regression.md
    - introduction/why-use-river.md
    - introduction/next-steps.md
    - introduction/related-projects.md
  - Recipes:
    - recipes/reading-data.md
    - recipes/model-evaluation.md
    - recipes/pipelines.md
    - recipes/feature-extraction.md
    - recipes/saving-loading.md
    - recipes/mini-batching.md
    - recipes/active-learning.md
    - recipes/bandits-101.md
    - recipes/cloning-and-mutating.md
    - recipes/rolling-computations.md
  - API:
    - api/overview.md
    - active:
      - api/active/EntropySampler.md
      - base:
        - api/active/base/ActiveLearningClassifier.md
    - anomaly:
      - api/anomaly/GaussianScorer.md
      - api/anomaly/HalfSpaceTrees.md
      - api/anomaly/LocalOutlierFactor.md
      - api/anomaly/OneClassSVM.md
      - api/anomaly/PredictiveAnomalyDetection.md
      - api/anomaly/QuantileFilter.md
      - api/anomaly/StandardAbsoluteDeviation.md
      - api/anomaly/ThresholdFilter.md
      - base:
        - api/anomaly/base/AnomalyDetector.md
        - api/anomaly/base/AnomalyFilter.md
        - api/anomaly/base/SupervisedAnomalyDetector.md
    - bandit:
      - api/bandit/BayesUCB.md
      - api/bandit/EpsilonGreedy.md
      - api/bandit/Exp3.md
      - api/bandit/LinUCBDisjoint.md
      - api/bandit/RandomPolicy.md
      - api/bandit/ThompsonSampling.md
      - api/bandit/UCB.md
      - api/bandit/evaluate.md
      - api/bandit/evaluate-offline.md
      - base:
        - api/bandit/base/ContextualPolicy.md
        - api/bandit/base/Policy.md
      - datasets:
        - api/bandit/datasets/BanditDataset.md
        - api/bandit/datasets/NewsArticles.md
      - envs:
        - api/bandit/envs/CandyCaneContest.md
        - api/bandit/envs/KArmedTestbed.md
    - base:
      - api/base/Base.md
      - api/base/BaseTransformer.md
      - api/base/BinaryDriftAndWarningDetector.md
      - api/base/BinaryDriftDetector.md
      - api/base/Classifier.md
      - api/base/Clusterer.md
      - api/base/DriftAndWarningDetector.md
      - api/base/DriftDetector.md
      - api/base/Ensemble.md
      - api/base/Estimator.md
      - api/base/MiniBatchClassifier.md
      - api/base/MiniBatchRegressor.md
      - api/base/MiniBatchSupervisedTransformer.md
      - api/base/MiniBatchTransformer.md
      - api/base/MultiLabelClassifier.md
      - api/base/MultiTargetRegressor.md
      - api/base/Regressor.md
      - api/base/SupervisedTransformer.md
      - api/base/Transformer.md
      - api/base/Wrapper.md
      - api/base/WrapperEnsemble.md
    - cluster:
      - api/cluster/CluStream.md
      - api/cluster/DBSTREAM.md
      - api/cluster/DenStream.md
      - api/cluster/KMeans.md
      - api/cluster/ODAC.md
      - api/cluster/STREAMKMeans.md
      - api/cluster/TextClust.md
    - compat:
      - api/compat/River2SKLClassifier.md
      - api/compat/River2SKLClusterer.md
      - api/compat/River2SKLRegressor.md
      - api/compat/River2SKLTransformer.md
      - api/compat/SKL2RiverClassifier.md
      - api/compat/SKL2RiverRegressor.md
      - api/compat/convert-river-to-sklearn.md
      - api/compat/convert-sklearn-to-river.md
    - compose:
      - api/compose/Discard.md
      - api/compose/FuncTransformer.md
      - api/compose/Grouper.md