from collections.abc import Callable, ItemsView, Iterable, Iterator, KeysView, ValuesView
from typing import Any

import numpy.typing

def get_union_keys(left: VectorDict, right: VectorDict) -> Iterator[Any]: ...
def get_intersection_keys(left: VectorDict, right: VectorDict) -> Iterator[Any]: ...

class VectorDict:
    def __init__(
        self,
        data: VectorDict | dict[Any, object] | None = None,
        default_factory: Callable[[], Any | None] | None = None,
        mask: VectorDict | set[Any] | None = None,
        copy: bool = False,
    ) -> None: ...
    def with_mask(self, mask: VectorDict | set[Any] | None, copy: bool = False) -> VectorDict: ...
    def to_dict(self) -> dict[Any, object]: ...
    def to_numpy(self, fields: Iterable[Any]) -> numpy.typing.NDArray[Any]: ...
    def __contains__(self, key: Any) -> bool: ...
    def __delitem__(self, key: Any) -> None: ...
    def __format__(self, format_spec: str) -> str: ...
    def __getitem__(self, key: Any) -> object: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, key: Any, value: object) -> None: ...
    def __str__(self) -> str: ...
    def clear(self) -> None: ...
    def get(self, key: Any, *args: object, **kwargs: object) -> object: ...
    def items(self) -> ItemsView[Any, object]: ...
    def keys(self) -> KeysView[Any]: ...
    def pop(self, *args: object, **kwargs: object) -> object: ...
    def popitem(self) -> tuple[Any, object]: ...
    def setdefault(self, key: Any, *args: object, **kwargs: object) -> object | None: ...
    def update(self, *args: object, **kwargs: object) -> None: ...
    def values(self) -> ValuesView[object]: ...
    def __eq__(left, right: object) -> bool: ...
    def __add__(left, right: object) -> VectorDict: ...
    def __radd__(self, other: object) -> VectorDict: ...
    def __iadd__(self, other: object) -> VectorDict: ...
    def __sub__(left, right: object) -> VectorDict: ...
    def __rsub__(self, other: object) -> VectorDict: ...
    def __isub__(self, other: object) -> VectorDict: ...
    def __mul__(left, right: object) -> VectorDict: ...
    def __rmul__(self, other: object) -> VectorDict: ...
    def __imul__(self, other: object) -> VectorDict: ...
    def __truediv__(left, right: object) -> VectorDict: ...
    def __rtruediv__(self, other: object) -> VectorDict: ...
    def __itruediv__(self, other: object) -> VectorDict: ...
    def __pow__(left, right: object) -> VectorDict: ...
    def __ipow__(self, other: object) -> VectorDict: ...
    def __matmul__(left, right: VectorDict) -> object: ...
    def __neg__(self) -> VectorDict: ...
    def __pos__(self) -> VectorDict: ...
    def __abs__(self) -> VectorDict: ...
    def abs(self) -> VectorDict: ...
    def min(self) -> object: ...
    def max(self) -> object: ...
    def minimum(self, other: object) -> VectorDict: ...
    def maximum(self, other: object) -> VectorDict: ...
