from collections.abc import Callable, ItemsView, Iterable, Iterator, KeysView, ValuesView
from typing import Any, Generic, Self, TypeVar

import numpy.typing

KT1 = TypeVar("KT1")
KT2 = TypeVar("KT2")

def get_union_keys(
    left: VectorDict[KT1, Any], right: VectorDict[KT2, Any]
) -> Iterator[KT1 | KT2]: ...
def get_intersection_keys(
    left: VectorDict[KT1, Any], right: VectorDict[KT2, Any]
) -> Iterator[KT1 | KT2]: ...

KT = TypeVar("KT")
VT = TypeVar("VT")

class VectorDict(Generic[KT, VT]):
    def __init__(
        self,
        data: VectorDict[KT, VT] | dict[KT, VT] | None = None,
        default_factory: Callable[[], VT] | None = None,
        mask: Iterable[KT] | None = None,
        copy: bool = False,
    ) -> None: ...
    def with_mask(self, mask: Iterable[KT] | None, copy: bool = False) -> Self: ...
    def to_dict(self) -> dict[KT, VT]: ...
    def to_numpy(self, fields: Iterable[KT]) -> numpy.typing.NDArray[Any]: ...
    def __contains__(self, key: KT) -> bool: ...
    def __delitem__(self, key: KT) -> None: ...
    def __format__(self, format_spec: str) -> str: ...
    def __getitem__(self, key: KT) -> VT: ...
    def __iter__(self) -> Iterator[KT]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, key: KT, value: VT) -> None: ...
    def __str__(self) -> str: ...
    def clear(self) -> None: ...
    def get(self, key: KT, *args: object, **kwargs: object) -> VT: ...
    def items(self) -> ItemsView[KT, VT]: ...
    def keys(self) -> KeysView[KT]: ...
    def pop(self, *args: object, **kwargs: object) -> VT: ...
    def popitem(self) -> tuple[KT, VT]: ...
    def setdefault(self, key: KT, *args: object, **kwargs: object) -> VT | None: ...
    def update(self, *args: object, **kwargs: object) -> None: ...
    def values(self) -> ValuesView[VT]: ...
    def __eq__(self, right: object) -> bool: ...
    def __add__(self, right: object) -> Self: ...
    def __radd__(self, other: object) -> Self: ...
    def __iadd__(self, other: object) -> Self: ...
    def __sub__(self, right: object) -> Self: ...
    def __rsub__(self, other: object) -> Self: ...
    def __isub__(self, other: object) -> Self: ...
    def __mul__(self, right: object) -> Self: ...
    def __rmul__(self, other: object) -> Self: ...
    def __imul__(self, other: object) -> Self: ...
    def __truediv__(self, right: object) -> Self: ...
    def __rtruediv__(self, other: object) -> Self: ...
    def __itruediv__(self, other: object) -> Self: ...
    def __pow__(self, right: object) -> Self: ...
    def __ipow__(self, other: object) -> Self: ...
    def __matmul__(self, right: VectorDict[KT, VT]) -> VT: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def isub_scaled(self, other: object, scalar: object) -> Self: ...
    def iadd_scaled(self, other: object, scalar: object) -> Self: ...
    def abs(self) -> Self: ...
    def min(self) -> VT: ...
    def max(self) -> VT: ...
    def minimum(self, other: object) -> Self: ...
    def maximum(self, other: object) -> Self: ...
    def euclidean_distance(self, other: VectorDict[KT, VT] | dict[KT, VT]) -> float: ...

def euclidean_distance_dict(a: dict[Any, float], b: dict[Any, float]) -> float: ...
def euclidean_distance_tuple(a: tuple[float, ...], b: tuple[float, ...]) -> float: ...
def lazy_search_euclidean(
    query: tuple[Any, ...], window: Any, n_neighbors: int
) -> tuple[list[Any], list[float]]: ...
