class AdaptiveWindowing:
    def __init__(
        self,
        delta: float = 0.002,
        clock: int = 32,
        max_buckets: int = 5,
        min_window_length: int = 5,
        grace_period: int = 10,
    ) -> None: ...

    @property
    def variance_in_window(self) -> float: ...

    def update(self, value: float) -> bool: ...
    def get_n_detections(self) -> int: ...
    def get_width(self) -> float: ...
    def get_total(self) -> float: ...
    def get_variance(self) -> float: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getstate__(self) -> bytes: ...
    def __getnewargs__(self) -> tuple[float, int, int, int, int]: ...
