from collections.abc import Sequence

class RsQuantile:
    def __init__(self, q: float | None = None) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class RsEWMean:
    def __init__(self, alpha: float) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[float]: ...

class RsEWVar:
    def __init__(self, alpha: float) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[float]: ...

class RsIQR:
    def __init__(self, q_inf: float, q_sup: float) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[float, float]: ...

class RsKurtosis:
    def __init__(self, bias: bool) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[bool]: ...

class RsPeakToPeak:
    def __init__(self) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class RsSkew:
    def __init__(self, bias: bool) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[bool]: ...

class RsRollingQuantile:
    def __init__(self, q: float, window_size: int) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[float, int]: ...

class RsRollingIQR:
    def __init__(self, q_inf: float, q_sup: float, window_size: int) -> None: ...
    def update(self, x: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[float, float, int]: ...

class RsRollingROCAUC:
    def __init__(self, positive_label: int, window_size: int) -> None: ...
    def update(self, label: int, score: float) -> None: ...
    def update_many(self, labels: Sequence[int], scores: Sequence[float]) -> None: ...
    def revert(self, label: int, score: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[int, int]: ...

class RsRollingPRAUC:
    def __init__(self, positive_label: int, window_size: int) -> None: ...
    def update(self, label: int, score: float) -> None: ...
    def update_many(self, labels: Sequence[int], scores: Sequence[float]) -> None: ...
    def revert(self, label: int, score: float) -> None: ...
    def get(self) -> float: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getnewargs__(self) -> tuple[int, int]: ...

def expected_mutual_info(n_samples: float, a: Sequence[int], b: Sequence[int]) -> float: ...
