from collections.abc import (
    Callable,
    ItemsView,
    Iterable,
    Iterator,
    KeysView,
    Mapping,
    Sequence,
    ValuesView,
)
from typing import Any, Generic, Literal, Self, TypeVar, overload

import numpy.typing

KT = TypeVar("KT")
VT = TypeVar("VT")

class VectorDict(Generic[KT, VT]):
    def __init__(
        self,
        data: VectorDict[KT, VT] | Mapping[KT, VT] | None = None,
        default_factory: Callable[[], VT] | None = None,
        mask: Iterable[KT] | None = None,
        copy: bool = False,
    ) -> None: ...
    def with_mask(self, mask: Iterable[KT] | None, copy: bool = False) -> Self: ...
    @staticmethod
    def from_scaled(values: dict[KT, float], scalar: float) -> VectorDict[KT, float]: ...
    def to_dict(self) -> dict[KT, VT]: ...
    def to_numpy(self, fields: Iterable[KT]) -> numpy.typing.NDArray[Any]: ...
    def __contains__(self, key: KT) -> bool: ...
    def __delitem__(self, key: KT) -> None: ...
    def __format__(self, spec: str) -> str: ...
    def __getitem__(self, key: KT) -> VT: ...
    def __iter__(self) -> Iterator[KT]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, key: KT, value: VT) -> None: ...
    def __str__(self) -> str: ...
    def clear(self) -> None: ...
    @overload
    def get(self, key: KT) -> VT | None: ...
    @overload
    def get(self, key: KT, default: VT) -> VT: ...
    def items(self) -> ItemsView[KT, VT]: ...
    def keys(self) -> KeysView[KT]: ...
    def pop(self, default: VT | None = None) -> VT: ...
    def popitem(self) -> tuple[KT, VT]: ...
    def setdefault(self, key: KT, default: VT | None = None) -> VT | None: ...
    def update(self, other: Mapping[KT, VT]) -> None: ...
    def values(self) -> ValuesView[VT]: ...
    def __eq__(self, right: object) -> bool: ...
    def __add__(self, other: object) -> Self: ...
    def __radd__(self, other: object) -> Self: ...
    def __iadd__(self, other: object) -> Self: ...
    def __sub__(self, other: object) -> Self: ...
    def __rsub__(self, other: object) -> Self: ...
    def __isub__(self, other: object) -> Self: ...
    def __mul__(self, other: object) -> Self: ...
    def __rmul__(self, other: object) -> Self: ...
    def __imul__(self, other: object) -> Self: ...
    def __truediv__(self, other: object) -> Self: ...
    def __rtruediv__(self, other: object) -> Self: ...
    def __itruediv__(self, other: object) -> Self: ...
    def __pow__(self, other: object) -> Self: ...
    def __ipow__(self, other: object) -> Self: ...
    def __matmul__(self, right: VectorDict[KT, VT]) -> VT: ...
    def dot(self, values: Mapping[KT, float]) -> float: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def iadd_scaled(self, other: VectorDict[KT, VT], scale: VT) -> Self: ...
    def isub_scaled(self, other: VectorDict[KT, VT], scale: VT) -> Self: ...
    def update_ema(
        self, other: VectorDict[KT, VT], decay: float, square: bool = False
    ) -> VectorDict[KT, VT]: ...
    def abs(self) -> Self: ...
    def min(self) -> VT: ...
    def max(self) -> VT: ...
    def minimum(self, other: object) -> Self: ...
    def maximum(self, other: object) -> Self: ...
    def __reduce__(
        self,
    ) -> tuple[
        type, tuple[dict[KT, VT], Callable[[], VT] | None, Iterable[KT] | None, Literal[True]]
    ]: ...
    def __deepcopy__(self, _memo: object) -> VectorDict[KT, VT]: ...
    def __copy__(self) -> VectorDict[KT, VT]: ...
    def euclidean_distance(self, other: VectorDict[KT, VT] | Mapping[KT, VT]) -> float: ...

def euclidean_distance_dict(a: Mapping[Any, float], b: Mapping[Any, float]) -> float: ...
def euclidean_distance_squared_dict(a: Mapping[Any, float], b: Mapping[Any, float]) -> float: ...
def euclidean_distance_tuple(
    a: tuple[Mapping[Any, float], Any], b: tuple[Mapping[Any, float], Any]
) -> float: ...
def lazy_search_euclidean(
    query: Sequence[Mapping[Any, float]],
    window: Iterable[Sequence[Sequence[Mapping[Any, float]]]],
    n_neighbors: int,
) -> tuple[list[Sequence[Mapping[Any, float]]], list[float]]: ...
