from typing import Generic, TypeVar

from _typeshed import Incomplete

KT = TypeVar("KT")
VT = TypeVar("VT")

class VectorDict(Generic[KT, VT]):
    def __init__(
        self,
        data: Incomplete | None = None,
        default_factory: Incomplete | None = None,
        mask: Incomplete | None = None,
        copy: bool = False,
    ) -> None: ...
    def with_mask(self, mask: Incomplete | None, copy: bool = False) -> VectorDict[KT, VT]: ...
    def to_dict(self) -> dict[Incomplete, Incomplete]: ...
    def to_numpy(self, fields: Incomplete) -> Incomplete: ...
    def __contains__(self, key: Incomplete) -> bool: ...
    def __delitem__(self, key: Incomplete) -> None: ...
    def __format__(self, format_spec: Incomplete) -> Incomplete: ...
    def __getitem__(self, key: Incomplete) -> Incomplete: ...
    def __iter__(self) -> Incomplete: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
    def __str__(self) -> str: ...
    def clear(self) -> None: ...
    def get(self, key: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def items(self) -> Incomplete: ...
    def keys(self) -> Incomplete: ...
    def pop(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete: ...
    def popitem(self) -> Incomplete: ...
    def setdefault(
        self, key: Incomplete, *args: Incomplete, **kwargs: Incomplete
    ) -> Incomplete: ...
    def update(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def values(self) -> Incomplete: ...
    def __eq__(self, value: Incomplete) -> bool: ...
    def __add__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __radd__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __iadd__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __sub__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __rsub__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __isub__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __mul__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __rmul__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __imul__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __truediv__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __rtruediv__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __itruediv__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __pow__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __ipow__(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __matmul__(self, right: Incomplete) -> Incomplete: ...
    def __neg__(self) -> VectorDict[KT, VT]: ...
    def __pos__(self) -> VectorDict[KT, VT]: ...
    def __abs__(self) -> VectorDict[KT, VT]: ...
    def iadd_scaled(self, other: Incomplete, scalar: Incomplete) -> VectorDict[KT, VT]: ...
    def isub_scaled(self, other: Incomplete, scalar: Incomplete) -> VectorDict[KT, VT]: ...
    def abs(self) -> VectorDict[KT, VT]: ...
    def min(self) -> Incomplete: ...
    def max(self) -> Incomplete: ...
    def minimum(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def maximum(self, other: Incomplete) -> VectorDict[KT, VT]: ...
    def __reduce__(self) -> Incomplete: ...
    def __deepcopy__(self, _memo: Incomplete) -> VectorDict[KT, VT]: ...
    def __copy__(self) -> VectorDict[KT, VT]: ...
    def euclidean_distance(self, other: Incomplete) -> float: ...

def euclidean_distance_dict(
    a: dict[Incomplete, Incomplete],
    b: dict[Incomplete, Incomplete],
) -> float: ...
def euclidean_distance_tuple(
    a: tuple[Incomplete, ...],
    b: tuple[Incomplete, ...],
) -> float: ...
def lazy_search_euclidean(
    query: tuple[Incomplete, ...],
    window: Incomplete,
    n_neighbors: int,
) -> tuple[Incomplete, Incomplete]: ...
