from __future__ import annotations

class RsQuantile:
    def __init__(self, q: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsEWMean:
    def __init__(self, alpha: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsEWVar:
    def __init__(self, alpha: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsIQR:
    def __init__(self, q_inf: float, q_sup: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsKurtosis:
    def __init__(self, bias: bool): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsPeakToPeak:
    def __init__(self): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsSkew:
    def __init__(self, bias: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsRollingQuantile:
    def __init__(self, q: float, window_size: int): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsRollingIQR:
    def __init__(self, q_inf: float, q_sup: float, window_size: int): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsRollingROCAUC:
    def __init__(self, positive_label: int, window_size: int): ...
    def update(self, label: int, score: float): ...
    def update_many(self, labels: list[int], scores: list[float]): ...
    def revert(self, label: int, score: float): ...
    def get(self) -> float: ...

class RsRollingPRAUC:
    def __init__(self, positive_label: int, window_size: int): ...
    def update(self, label: int, score: float): ...
    def update_many(self, labels: list[int], scores: list[float]): ...
    def revert(self, label: int, score: float): ...
    def get(self) -> float: ...

class AdaptiveWindowing:
    def __init__(
        self,
        delta: float = 0.002,
        clock: int = 32,
        max_buckets: int = 5,
        min_window_length: int = 5,
        grace_period: int = 10,
    ) -> None: ...
    def update(self, value: float) -> bool: ...
    def get_n_detections(self) -> int: ...
    def get_width(self) -> float: ...
    def get_total(self) -> float: ...
    def get_variance(self) -> float: ...
    @property
    def variance_in_window(self) -> float: ...

def expected_mutual_info(n_samples: float, a: list[int], b: list[int]) -> float: ...

class VectorDict:
    def __init__(
        self,
        data: object | None = None,
        default_factory: object | None = None,
        mask: object | None = None,
        copy: bool = False,
    ) -> None: ...
    def __getitem__(self, key: object) -> object: ...
    def __setitem__(self, key: object, value: object) -> None: ...
    def __delitem__(self, key: object) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> object: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __add__(self, other: object) -> VectorDict: ...
    def __radd__(self, other: object) -> VectorDict: ...
    def __iadd__(self, other: object) -> VectorDict: ...
    def __sub__(self, other: object) -> VectorDict: ...
    def __rsub__(self, other: object) -> VectorDict: ...
    def __isub__(self, other: object) -> VectorDict: ...
    def __mul__(self, other: object) -> VectorDict: ...
    def __rmul__(self, other: object) -> VectorDict: ...
    def __imul__(self, other: object) -> VectorDict: ...
    def __truediv__(self, other: object) -> VectorDict: ...
    def __rtruediv__(self, other: object) -> VectorDict: ...
    def __itruediv__(self, other: object) -> VectorDict: ...
    def __pow__(self, other: object, modulo: object | None = None) -> VectorDict: ...
    def __ipow__(self, other: object, modulo: object | None = None) -> VectorDict: ...
    def __matmul__(self, other: VectorDict) -> object: ...
    def __neg__(self) -> VectorDict: ...
    def __pos__(self) -> VectorDict: ...
    def __abs__(self) -> VectorDict: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def with_mask(self, mask: object | None, copy: bool = False) -> VectorDict: ...
    def to_dict(self) -> dict: ...
    def to_numpy(self, fields: object) -> object: ...
    def clear(self) -> None: ...
    def get(self, key: object, *args: object, **kwargs: object) -> object: ...
    def items(self) -> object: ...
    def keys(self) -> object: ...
    def pop(self, *args: object, **kwargs: object) -> object: ...
    def popitem(self) -> object: ...
    def setdefault(self, key: object, *args: object, **kwargs: object) -> object: ...
    def update(self, *args: object, **kwargs: object) -> None: ...
    def values(self) -> object: ...
    def iadd_scaled(self, other: object, scalar: object) -> VectorDict: ...
    def isub_scaled(self, other: object, scalar: object) -> VectorDict: ...
    def abs(self) -> VectorDict: ...
    def min(self) -> object: ...
    def max(self) -> object: ...
    def minimum(self, other: object) -> VectorDict: ...
    def maximum(self, other: object) -> VectorDict: ...
    def euclidean_distance(self, other: object) -> float: ...

def euclidean_distance_dict(a: dict, b: dict) -> float: ...
def euclidean_distance_tuple(a: tuple, b: tuple) -> float: ...
def lazy_search_euclidean(query: tuple, window: object, n_neighbors: int) -> tuple[list, list]: ...
