from __future__ import annotations

from collections.abc import Callable, Iterable, ItemsView, Iterator, KeysView, ValuesView
from typing import Any, Generic, Self, TypeVar, overload

import numpy.typing

KT = TypeVar("KT")
VT = TypeVar("VT")
T = TypeVar("T")

class RsQuantile:
    def __init__(self, q: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsEWMean:
    def __init__(self, alpha: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsEWVar:
    def __init__(self, alpha: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsIQR:
    def __init__(self, q_inf: float, q_sup: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsKurtosis:
    def __init__(self, bias: bool): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsPeakToPeak:
    def __init__(self): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsSkew:
    def __init__(self, bias: float): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsRollingQuantile:
    def __init__(self, q: float, window_size: int): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsRollingIQR:
    def __init__(self, q_inf: float, q_sup: float, window_size: int): ...
    def update(self, x: float): ...
    def get(self) -> float: ...

class RsRollingROCAUC:
    def __init__(self, positive_label: int, window_size: int): ...
    def update(self, label: int, score: float): ...
    def update_many(self, labels: list[int], scores: list[float]): ...
    def revert(self, label: int, score: float): ...
    def get(self) -> float: ...

class RsRollingPRAUC:
    def __init__(self, positive_label: int, window_size: int): ...
    def update(self, label: int, score: float): ...
    def update_many(self, labels: list[int], scores: list[float]): ...
    def revert(self, label: int, score: float): ...
    def get(self) -> float: ...

class AdaptiveWindowing:
    def __init__(
        self,
        delta: float = 0.002,
        clock: int = 32,
        max_buckets: int = 5,
        min_window_length: int = 5,
        grace_period: int = 10,
    ) -> None: ...
    def update(self, value: float) -> bool: ...
    def get_n_detections(self) -> int: ...
    def get_width(self) -> float: ...
    def get_total(self) -> float: ...
    def get_variance(self) -> float: ...
    @property
    def variance_in_window(self) -> float: ...

def expected_mutual_info(n_samples: float, a: list[int], b: list[int]) -> float: ...

class VectorDict(Generic[KT, VT]):
    def __init__(
        self,
        data: VectorDict[KT, VT] | dict[KT, VT] | None = None,
        default_factory: Callable[[], VT] | None = None,
        mask: Iterable[KT] | None = None,
        copy: bool = False,
    ) -> None: ...
    def with_mask(self, mask: Iterable[KT] | None, copy: bool = False) -> Self: ...
    def to_dict(self) -> dict[KT, VT]: ...
    def to_numpy(self, fields: Iterable[KT]) -> numpy.typing.NDArray[Any]: ...

    def __contains__(self, key: KT) -> bool: ...
    def __delitem__(self, key: KT) -> None: ...
    def __getitem__(self, key: KT) -> VT: ...
    def __setitem__(self, key: KT, value: VT) -> None: ...
    def __iter__(self) -> Iterator[KT]: ...
    def __len__(self) -> int: ...
    def __format__(self, format_spec: str) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    # Stays `object` per the Python data-model convention for __eq__.
    def __eq__(self, right: object) -> bool: ...

    def clear(self) -> None: ...
    def items(self) -> ItemsView[KT, VT]: ...
    def keys(self) -> KeysView[KT]: ...
    def values(self) -> ValuesView[VT]: ...
    def popitem(self) -> tuple[KT, VT]: ...

    @overload
    def get(self, key: KT) -> VT | None: ...
    @overload
    def get(self, key: KT, default: VT) -> VT: ...
    @overload
    def get(self, key: KT, default: T) -> VT | T: ...

    @overload
    def pop(self, key: KT) -> VT: ...
    @overload
    def pop(self, key: KT, default: VT) -> VT: ...
    @overload
    def pop(self, key: KT, default: T) -> VT | T: ...

    @overload
    def setdefault(self, key: KT) -> VT | None: ...
    @overload
    def setdefault(self, key: KT, default: VT) -> VT: ...

    def update(self, *args: Any, **kwargs: Any) -> None: ...

    def __add__(self, right: VectorDict[KT, VT] | VT) -> Self: ...
    def __radd__(self, other: VT) -> Self: ...
    def __iadd__(self, other: VectorDict[KT, VT] | VT) -> Self: ...
    def __sub__(self, right: VectorDict[KT, VT] | VT) -> Self: ...
    def __rsub__(self, other: VT) -> Self: ...
    def __isub__(self, other: VectorDict[KT, VT] | VT) -> Self: ...
    def __mul__(self, right: VectorDict[KT, VT] | VT) -> Self: ...
    def __rmul__(self, other: VT) -> Self: ...
    def __imul__(self, other: VectorDict[KT, VT] | VT) -> Self: ...
    def __truediv__(self, right: VectorDict[KT, VT] | VT) -> Self: ...
    def __rtruediv__(self, other: VT) -> Self: ...
    def __itruediv__(self, other: VectorDict[KT, VT] | VT) -> Self: ...
    def __pow__(self, right: VT, modulo: None = None) -> Self: ...
    def __ipow__(self, other: VT, modulo: None = None) -> Self: ...
    def __matmul__(self, right: VectorDict[KT, VT]) -> VT: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...

    def iadd_scaled(self, other: VectorDict[KT, VT], scalar: VT) -> Self: ...
    def isub_scaled(self, other: VectorDict[KT, VT], scalar: VT) -> Self: ...
    def abs(self) -> Self: ...
    def min(self) -> VT: ...
    def max(self) -> VT: ...
    def minimum(self, other: VectorDict[KT, VT] | VT) -> Self: ...
    def maximum(self, other: VectorDict[KT, VT] | VT) -> Self: ...
    def euclidean_distance(self, other: VectorDict[KT, VT] | dict[KT, VT]) -> float: ...

def euclidean_distance_dict(a: dict[Any, float], b: dict[Any, float]) -> float: ...
def euclidean_distance_tuple(
    a: tuple[dict[Any, float], Any], b: tuple[dict[Any, float], Any]
) -> float: ...
def lazy_search_euclidean(
    query: tuple[Any, ...], window: Any, n_neighbors: int
) -> tuple[list[Any], list[float]]: ...
