build-jupyter:
	    docker build -t skmultiflow/scikit-multiflow:jupyter -f dockerfiles/jupyter.Dockerfile .

build-python:
	    docker build -t skmultiflow/scikit-multiflow:latest -f dockerfiles/Dockerfile .

push-python:
	    docker push skmultiflow/scikit-multiflow:latest

push-jupyter:
	    docker push skmultiflow/scikit-multiflow:jupyter


