name: Install env

inputs:
  python-version:
    description: "Python version to use"
    required: true
  build-root:
    default: "true"
    options:
      - true
      - false

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}

    - name: Load cached virtual env
      id: cached-uv-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/uv.lock') }}

    - name: Install dependencies
      shell: bash
      if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
      run: uv sync --no-install-project

    - name: Build
      shell: bash
      if: ${{ inputs.build-root == 'true' }}
      run: uv sync
