# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SOURCEDIR     = .
BUILDDIR      = _build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

update_nb:
	jupyter nbconvert --execute --to notebook --inplace ../notebooks/*.ipynb --ExecutePreprocessor.timeout=-1

nb_to_html: update_nb
	rm -rf docs/notebooks
	mkdir -p docs/notebooks
	jupyter nbconvert --to html --output-dir notebooks ../notebooks/*.ipynb
