name: code-quality

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Download datasets
        run: uv run make download-datasets

      - name: Run tests
        run: uv run pytest

      - name: Install prek
        uses: taiki-e/install-action@cargo-binstall

      - name: Install prek binary
        run: cargo binstall prek --no-confirm

      - name: Cache prek hooks
        uses: actions/cache@v3
        with:
          path: ~/.cache/prek/
          key: prek|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run prek
        run: prek run --all-files
