name: dev-docs

on:
  push:
    branches: [main]

concurrency:
  group: dev-docs
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        uses: pandoc/actions/setup@v1

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build docs
        run: uv run make doc

      - name: Upload docs source
        uses: actions/upload-artifact@v4
        with:
          name: docs-source
          path: docs/linkified

  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: gh-pages-deploy
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Download docs source
        uses: actions/download-artifact@v4
        with:
          name: docs-source
          path: docs/linkified

      - name: Deploy docs
        env:
          GH_TOKEN: ${{ secrets.GitHubToken }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          uv run mike deploy dev --push --remote https://github.com/${{ github.repository }}.git
